config/routes.rb
Rails.application.routes.draw do

  get 'home/content'
  get "content/edit" => 'content#edit', :as => :edit

  get  '/set-captain',   to: 'roles#setCaptain',      as: "set_captain"
  get  '/set-mentor',    to: 'roles#setMentor' ,      as: "set_mentor"

  get  '/delete-mentor', to: 'roles#destroyMentor',   as: "del_mentor"
  get  '/delete-member', to: 'roles#destroyMember',   as: "del_member"

  get  '/join-group',    to: 'join_groups#joinGroup', as: "join_group"
  get  '/leave-group',    to: 'join_groups#leaveGroup', as: "leave_group"

  get  '/approve-content',    to: 'pendings#approveContent', as: "approve_content"
  get  '/decline-content',    to: 'pendings#declineContent', as: "decline_content"

  get  '/approve-member',    to: 'pendings#approveMember', as: "approve_member"
  get  '/decline-member',    to: 'pendings#declineMember', as: "decline_member"

  post  '/create-attendance',    to: 'attendances#create', as: "attendance_member"

  get  '/new-event-content',    to: 'events#newEvent', as: "new_event_content"


  root 'home#index'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  mount Ckeditor::Engine => '/ckeditor'

  resources :users, only: [:show,:update, :index]
  resources :attendances
  resources :groups do
    resources :contents,   except: [:show, :index]
    resources :members,    only: [:index, :create]
    resources :attendances
    resources :pendings
    resources :settings,    only: [:index]
    resources :events
  end
  resources :courses
  resources :details
end

app/controllers/pendings_controller.rb
class PendingsController < ApplicationController
  layout "layout_group"
  before_action :group

  def index
    @group = Group.find_by(id: params[:group_id])
    @contents = Content.where(group_id: @group.id,status: 2).order("endDate DESC").page(params[:page]).per(5)  
    @contentss = Content.where(group_id: @group.id,status: 1).order("endDate DESC").page(params[:page]).per(5)  
    @members = Role.where(roles: 3, status: 2 ,  group_id:  @group.id)
  end

  def approveContent
    @content = Content.where(id: params[:id], group_id: params[:group_id]).first  
    @content.update_attributes(status: 1)
    flash[:success] = "Approve content successfully"
    redirect_to group_pendings_path(@group)
  end

  def declineContent
    @content = Content.where(id: params[:id], group_id: params[:group_id]).first  
    @content.destroy
    flash[:danger] = "Decline content successfully"
    redirect_to group_pendings_path(@group)
  end

  def approveMember
    @member = Role.where(id: params[:id], group_id: params[:group_id]).first  
    @member.update_attributes(status: 1)
    flash[:success] = "Approve member successfully"
    redirect_to group_pendings_path(@group)
  end

  def declineMember
    @member = Role.where(id: params[:id], group_id: params[:group_id]).first  
    @member.destroy
    flash[:danger] = "Decline member successfully"
    redirect_to group_pendings_path(@group)
  end

  private 
  def group
    @group = Group.find_by(params[:group_id])
  end

end

app/helpers/pendings_helper.rb
module PendingsHelper

    def pending_item
        @contents_pending = Content.where(group_id: @group.id, status: 2)
        @members_pending = Role.where(group_id: @group.id, status: 2)
        @pending_item = @contents_pending.size + @members_pending.size 
    end

    def role_permiss?
       
    end
end

app/views/pendings/index.html.erb
<!-- main -->
    <div id="main">
        <div class="container">
            <div class="row">
                
                <div class="col-sm-9 col-lg-8 main-mid">
                  <div class="nav-profile" style="margin-left: 12px;"> 

                    <ul class="nav nav-tabs">
                        <li class="active"><a data-toggle="tab" href="#home" style="font-size:19px;">Member</a></li>
                        <li><a data-toggle="tab" href="#menu3" style="font-size:19px;">Content</a></li>
                    </ul>

                </div>
                <div class="tab-content" style="padding-left: 12px;">
                  <div id="home" class="tab-pane fade in active">
                    <% if @members.blank? %>
                    <h2 align="center">No Member just yet!</h2>
                    <% else %>
                    <% @members.each do |content| %>
                    <div class="row">
                      <div class="">
                        <div class="row">
                          <div class="col-xs-4">
                            <div>
                              <%= image_tag( content.user.pictures, alt: "Rails", class: "background-image-content" )%>
                            </div>
                            <div class="content-group">
                              <div class="content-email">

                                <div class="content-status">  
                                  <h3 align="center">Pending</h3>
                                </div>
                              </div>
                            </div>
                          </div>
                          <div class="col-xs-8">
                            <div class="row">
                              <div class="col-xs-8">
                                  <p><%= content.user.fullname %></p>
                                  <p><%= content.user.email %></p>
                                  <p><%= content.created_at %></p>
                                    <%= link_to  "Decline", decline_member_path(group_id: content.group.id, id: content.id), class: "btn btn-danger" %>
                                    <%= link_to  "Approve", approve_member_path(group_id: content.group.id, id: content.id),  class: "btn btn-info" %>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                    <% end %>
                    <% end %>
                  </div>
                  
                  <div id="menu3" class="tab-pane fade">
                    <% if @contents.blank? %>
                    <h2 align="center">No Content just yet!</h2>
                    <% else %>

                    <% @contents.each do |content| %>
                    <div class="row">
                      <div class="">
                        <div class="row">
                          <div class="col-xs-4">
                            <div>
                              <%= image_tag( "ava.jpg", alt: "Rails", class: "background-image-content" )%>
                            </div>
                            <div class="content-group">
                              <div class="content-email">

                                <div class="content-status">
                          
                                  <h3 align="center">Pending</h3>
                                
                                </div>

                                <span>
                                  <img src="<%= content.user.pictures%>" alt="" id="avatar">
                                  <%= content.user.fullname %> <br>
                                  <div class="content-create-sz">
                                    <%= content.created_at %>
                                  </div>
                                </span>
                              </div>
                        
                                <div class="content-create-sz">
                                  <span> Start:
                                    <%=  content.startDate %></span>
                                  </br>
                                  <span>End:
                                    <%=  content.endDate %></span>
                                  </br>
                                  <span>Level:
                                    <%=  content.level %></span>
                                </div>
                            </div>
                          </div>
                          <div class="col-xs-8">
                            <div class="row">
                              <div class="col-xs-8">
                                <div class="content-title">
                                  <%= content.title %>
                                </div>
                              </div>
                              <div class="col-xs-4">
                                <div class="menu-content-drop">
                              
                                </div>
                              </div>
                              <div class="row">
                                <div class="content-body">
                                  <div class="col-xs-8">
                                    <p><%= truncate sanitize(content.description, tags: [], attributes: []), length: 300 %></p>

                                    <%= link_to  "Decline", decline_content_path(group_id: content.group.id, id: content.id), class: "btn btn-danger" %>
                                    <%= link_to  "Approve", approve_content_path(group_id: content.group.id, id: content.id), class: "btn btn-info" %>
                                 
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                    <% end %>
                   
                    <% end %>
                  </div>
                  <div id="product-modal" class="modal fade"></div>
                  
                  </div>
                </div>
                <div class="col-sm-3 col-lg-4 main-right">
                    <div class="box-main">
                        <h3 class="card-header" id="monthAndYear"></h3>
                        <table class="table table-bordered table-responsive-sm" id="calendar">
                            <thead>
                                <tr>
                                    <th>Sun</th>
                                    <th>Mon</th>
                                    <th>Tue</th>
                                    <th>Wed</th>
                                    <th>Thu</th>
                                    <th>Fri</th>
                                    <th>Sat</th>
                                </tr>
                            </thead>

                            <tbody id="calendar-body">

                            </tbody>
                        </table>

                        <div class="form-inline">

                            <button class="btn btn-outline-primary col-sm-6" id="previous"
                                onclick="previous()">Previous</button>

                            <button class="btn btn-outline-primary col-sm-6" id="next" onclick="next()">Next</button>
                        </div>
                        <br />
                        <form class="form-inline">
                            <label class="lead mr-2 ml-2" for="month"> Jump To: </label>
                            <select class="form-control col-sm-4" name="month" id="month" onchange="jump()">
                                <option value=0>Jan</option>
                                <option value=1>Feb</option>
                                <option value=2>Mar</option>
                                <option value=3>Apr</option>
                                <option value=4>May</option>
                                <option value=5>Jun</option>
                                <option value=6>Jul</option>
                                <option value=7>Aug</option>
                                <option value=8>Sep</option>
                                <option value=9>Oct</option>
                                <option value=10>Nov</option>
                                <option value=11>Dec</option>
                            </select>


                            <label for="year"></label><select class="form-control col-sm-4" name="year" id="year"
                                onchange="jump()">
                                <option value=1990>1990</option>
                                <option value=1991>1991</option>
                                <option value=1992>1992</option>
                                <option value=1993>1993</option>
                                <option value=1994>1994</option>
                                <option value=1995>1995</option>
                                <option value=1996>1996</option>
                                <option value=1997>1997</option>
                                <option value=1998>1998</option>
                                <option value=1999>1999</option>
                                <option value=2000>2000</option>
                                <option value=2001>2001</option>
                                <option value=2002>2002</option>
                                <option value=2003>2003</option>
                                <option value=2004>2004</option>
                                <option value=2005>2005</option>
                                <option value=2006>2006</option>
                                <option value=2007>2007</option>
                                <option value=2008>2008</option>
                                <option value=2009>2009</option>
                                <option value=2010>2010</option>
                                <option value=2011>2011</option>
                                <option value=2012>2012</option>
                                <option value=2013>2013</option>
                                <option value=2014>2014</option>
                                <option value=2015>2015</option>
                                <option value=2016>2016</option>
                                <option value=2017>2017</option>
                                <option value=2018>2018</option>
                                <option value=2019>2019</option>
                                <option value=2020>2020</option>
                                <option value=2021>2021</option>
                                <option value=2022>2022</option>
                                <option value=2023>2023</option>
                                <option value=2024>2024</option>
                                <option value=2025>2025</option>
                                <option value=2026>2026</option>
                                <option value=2027>2027</option>
                                <option value=2028>2028</option>
                                <option value=2029>2029</option>
                                <option value=2030>2030</option>
                            </select></form>
                    </div>
                </div>
            </div>

        </div>
    </div>
    <!-- end main -->